/*
 * 扩展接入
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003
 */
public class InlineResponse2003Test {
    private final InlineResponse2003 model = new InlineResponse2003();

    /**
     * Model tests for InlineResponse2003
     */
    @Test
    public void testInlineResponse2003() {
        // TODO: test InlineResponse2003
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'virifycodeid'
     */
    @Test
    public void virifycodeidTest() {
        // TODO: test virifycodeid
    }

    /**
     * Test the property 'virifyimage'
     */
    @Test
    public void virifyimageTest() {
        // TODO: test virifyimage
    }

}
