/*
 * 扩展接入
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-01T20:48:31.465+08:00[Asia/Shanghai]")
public class InlineObject2 {
  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ROBOTCODEID = "robotcodeid";
  @SerializedName(SERIALIZED_NAME_ROBOTCODEID)
  private String robotcodeid;

  public static final String SERIALIZED_NAME_ROBOTCODE = "robotcode";
  @SerializedName(SERIALIZED_NAME_ROBOTCODE)
  private String robotcode;


  public InlineObject2 phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * 手机号
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "手机号")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public InlineObject2 robotcodeid(String robotcodeid) {
    
    this.robotcodeid = robotcodeid;
    return this;
  }

   /**
   * 图片验证码ID
   * @return robotcodeid
  **/
  @ApiModelProperty(required = true, value = "图片验证码ID")

  public String getRobotcodeid() {
    return robotcodeid;
  }


  public void setRobotcodeid(String robotcodeid) {
    this.robotcodeid = robotcodeid;
  }


  public InlineObject2 robotcode(String robotcode) {
    
    this.robotcode = robotcode;
    return this;
  }

   /**
   * 图片验证码识别结果
   * @return robotcode
  **/
  @ApiModelProperty(required = true, value = "图片验证码识别结果")

  public String getRobotcode() {
    return robotcode;
  }


  public void setRobotcode(String robotcode) {
    this.robotcode = robotcode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject2 inlineObject2 = (InlineObject2) o;
    return Objects.equals(this.phone, inlineObject2.phone) &&
        Objects.equals(this.robotcodeid, inlineObject2.robotcodeid) &&
        Objects.equals(this.robotcode, inlineObject2.robotcode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, robotcodeid, robotcode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject2 {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    robotcodeid: ").append(toIndentedString(robotcodeid)).append("\n");
    sb.append("    robotcode: ").append(toIndentedString(robotcode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

