/*
 * 扩展接入
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.InlineObject2;
import org.openapitools.client.model.InlineObject3;
import org.openapitools.client.model.InlineObject4;
import org.openapitools.client.model.InlineResponse200;
import org.openapitools.client.model.InlineResponse2001;
import org.openapitools.client.model.InlineResponse2002;
import org.openapitools.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 4.Cookie登录
     *
     * Cookie无感登录jugugu获取用户信息。使用CookieToken和手机号登录菊咕咕获取信息，安全考虑该方法不会获得操作等级高的token。cookietoken只有有限的操作权限。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void friendLoginPostTest() throws ApiException {
        InlineObject4 inlineObject4 = null;
        InlineResponse2002 response = api.friendLoginPost(inlineObject4);

        // TODO: test validations
    }
    
    /**
     * 2.获取登录短信验证码
     *
     * 获取登录短信验证码，验证码重复发送周期为60秒。验证码有效时间为3分钟
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void juguguGetPhoneCodePostTest() throws ApiException {
        InlineObject2 inlineObject2 = null;
        InlineResponse2002 response = api.juguguGetPhoneCodePost(inlineObject2);

        // TODO: test validations
    }
    
    /**
     * 1.获得验证码图片
     *
     * 获取验证码图片，用于防止机器人。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void jugugugGetReleaseNFT1155PNGCodePostTest() throws ApiException {
        InlineObject3 inlineObject3 = null;
        InlineResponse2003 response = api.jugugugGetReleaseNFT1155PNGCodePost(inlineObject3);

        // TODO: test validations
    }
    
    /**
     * 转移NFT
     *
     * 转移指定ID的NFT，指定数量Amount，至指定用户区块链地址
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transferNFTPostTest() throws ApiException {
        InlineObject1 inlineObject1 = null;
        InlineResponse2001 response = api.transferNFTPost(inlineObject1);

        // TODO: test validations
    }
    
    /**
     * 查询用户NFT
     *
     * 查询指定合约用户徽章持有ID和对应的数量。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userNFTsPostTest() throws ApiException {
        InlineObject inlineObject = null;
        InlineResponse200 response = api.userNFTsPost(inlineObject);

        // TODO: test validations
    }
    
}
